# Generated by Django 2.2.1 on 2019-08-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nserie', models.CharField(max_length=12, verbose_name='Numero de Serie')),
                ('imagen', models.ImageField(null=True, upload_to='productos', verbose_name='Foto del producto')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('existencias', models.TextField(verbose_name='Existencias')),
                ('costo', models.TextField(verbose_name='Costo')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('marca', models.TextField(verbose_name='Marca')),
                ('modelo', models.TextField(verbose_name='Modelo')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updatedat', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Nombre de usuario')),
                ('pp', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.TextField(verbose_name='Contraseña')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('appelidos', models.TextField(verbose_name='Apellidos')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updatedat', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updatedat', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
                ('producto', models.ForeignKey(on_delete='cascade', to='inicio.Producto')),
                ('user', models.ForeignKey(on_delete='cascade', to='inicio.Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-createdat'],
            },
        ),
    ]
