# Generated by Django 2.2.1 on 2019-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_usuario_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updatedat', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['-createdat'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-createdat'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
