# Generated by Django 2.2.1 on 2019-08-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20190815_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete='cascade', to='inicio.Tipo'),
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.CharField(max_length=4, verbose_name='Porcentaje (ejem: 10%)')),
                ('porcentajeInt', models.IntegerField(max_length=3, verbose_name='Porcentaje (ejem: 10%)')),
                ('createdat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updatedat', models.DateTimeField(auto_now_add=True, verbose_name='Modificado')),
                ('producto', models.ForeignKey(on_delete='cascade', to='inicio.Producto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-createdat'],
            },
        ),
    ]
