# Generated by Django 2.2.1 on 2019-08-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20190815_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofertas',
            new_name='Oferta',
        ),
    ]
