# Generated by Django 2.2.1 on 2019-08-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20190815_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-createdat'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterField(
            model_name='oferta',
            name='porcentajeInt',
            field=models.IntegerField(verbose_name='Porcentaje (ejem: 10%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(verbose_name='Existencias'),
        ),
    ]
