# Generated by Django 2.2.1 on 2019-08-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_auto_20190816_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete='cascade', to='inicio.Oferta'),
        ),
    ]
