# Generated by Django 2.2.1 on 2019-08-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_auto_20190817_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
