# Generated by Django 2.2.1 on 2019-08-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20190817_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
