# Generated by Django 2.2.1 on 2019-08-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_auto_20190817_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pp',
            field=models.ImageField(default='profiles/default/pp.ppng', null=True, upload_to='profiles/', verbose_name='Foto de perfil'),
        ),
    ]
